{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-furrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/furrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/furrr/furrr_{{ version }}.tar.gz
  sha256: 0d91735e2e9be759b1ab148d115c2c7429b79740514778828e5dab631dc0e48b

build:
  merge_build_host: true  # [win]
  number: 1

  # could be changed to noarch
  #noarch: generic

  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]


requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base {{ r_version }}
    - r-ellipsis
    - r-future >=1.19.1
    - r-globals >=0.13.1
    - r-lifecycle >=0.2.0
    - r-purrr >=0.3.0
    - r-rlang >=0.3.0
    - r-vctrs >=0.3.2
  run:
    - r-base {{ r_version }}
    - r-ellipsis
    - r-future >=1.19.1
    - r-globals >=0.13.1
    - r-lifecycle >=0.2.0
    - r-purrr >=0.3.0
    - r-rlang >=0.3.0
    - r-vctrs >=0.3.2

test:
  commands:
    - $R -e "library('furrr')"           # [not win]
    - "\"%R%\" -e \"library('furrr')\""  # [win]

about:
  home: https://github.com/DavisVaughan/furrr
  license: MIT
  summary: Implementations of the family of map() functions from 'purrr' that can be resolved using any 'future'-supported backend, e.g. parallel on the local machine or distributed on a compute cluster.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider

