travis:
  secure:
    BINSTAR_TOKEN: hR/F5rD+BxkVoOaB6Je5Gb2ArG71ybPS3Q7G2FIlzl/8QvgEXWpP+sVS0FC6KU9+SjCmpj4PE7mKgmv+y/TBmYpNHm3x6mPUEsjnvvkWK35y1Cg+e3Alhx0wiFqVK7m3R8zaol8XWJiZBp/Ha/vPwxKP46xA0k4TdWXQBJTMmof1lX3crqMHIbiHdh9y1+JdoDo1ng48+qkbgiPEKIsMktqjsfgTmjGWmqKHdw0FEP9pri+Dm7U4A5N2x15V7rr8wiOyTMsZnhkl8fwB9AOqRqTCzgTACSEja21YwprM14P/B53phbSE1bzV/B4uz3QjC3y9IGPxLn06Et7X7KC2he+DC0Se68Fdo601hkaGXaFnpA0hbdzh1UgdCOfT2nYBfBs4cT5lJPHdiS2kMpk5R/K+c3B7cFFeEqjfSq+FPbpidk3pcUSIJL2RLue5+Dk2J9I1NGTZneTpubRpCPzLNeKOKrF2m1wdldVpZ45jQmIoKlhY0QHnuCPNYEJ8+2eYFhd0toqyvsqQUr6LH2/v79Aujgiy1lA2z7dD2hCWnbOyatAWPApF1G0rPwGaNHI9VWFTuYz3g7s6s6RCyvi0PUfXy2y69vKfN6dY0/0uRH7JjyYkle7k9rBPPJHNue8VgKtiqfM3a7siH+Tc0RmgzEyovV7hRn+j1SK7ykzPe5c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
